networks:
  app_network:
    driver: bridge

services:
  backend:
    build: ./backend
    container_name: app_backend
    ports:
      - '3000:3000'
    env_file:
      - ./backend/.env
    environment:
      - PORT=3000
      - NODE_ENV=production
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium
      - DATABASE_HOST=host.docker.internal
      - RABBITMQ_URL=rabbitmq:5672
      - REDIS_HOST=redis
    depends_on:
      - rabbitmq
      - redis
    networks:
      - app_network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=/api
    container_name: app_frontend
    ports:
      - '80:80'
    depends_on:
      - backend
    networks:
      - app_network
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"     
      - "15672:15672"   
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - app_network

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - app_network

volumes:
  rabbitmq_data: